### ISSUE TITLE
Deploy Rest-API to PyPi

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/rest-api#11]
### Parent Feature
#1 

### Task Description
As an AaC Developer, I want to deploy my Rest-API package to PyPi, so that end users are able to request it for install.

### Acceptance Criteria
- [ ] PyPi deployments are configured
  - [ ]  Include deploy-artifacts workflow from organization workflow starters 
- [ ] Package is published on PyPi
- [ ] A release on GitHub is published for the matching PyPi package content.
