### ISSUE TITLE
Move Legacy Rest-API to New Repository

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/rest-api#2]
### Parent Feature
#1 

### Task Description
As an AaC developer, I need to copy the legacy `rest-api` plugin from PreAPI repository to the new rest-api repository, so that it is properly separated from core baseline to work the refactor efforts.

Legacy: https://github.com/DevOps-MBSE/AaC-PreAPIChange

New: https://github.com/DevOps-MBSE/rest-api

### Acceptance Criteria
- [x] Documentation of `rest-api` is moved to the new repository.
- [x] Plugin directory for `rest-api` is moved to the new repository.
- [x] Unit tests for `rest-api` is moved to the new repository. 
- [x] .github directory for workflows and templates is moved to new repository.
- [x] Project configuration is moved to new repository.
